name: Build and test
on:
  push:
    branches:
      # - 'master'
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Coverage report
        run: mvn coveralls:report --define repoToken=${{ secrets.COVERALLS_TOKEN }}

      - name: Upload JaCoCo reports as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: target/site/jacoco/
